### ISSUE TITLE
New Accordion Styles

### ISSUE THREAD

**Issue by NowTV-Assurance** [sky-uk/nowtv-styleguide#79]
Both of these styles in the accordion aren't used in apps, the classes are only used in the docs, but the styles for them live in the styleguide. This doesn't make much sense? 

```scss
.now-accordion__icon {
  display: inline-block;
  margin-right: 15px;
  opacity: 0.7;
  width: 70px;
  height: 70px;
}

.now-accordion__text {
  display: inline-block;
  vertical-align: top;
}
```

@philtoms @tomatau 

If noone is using these (like we assume) they should probably be moved back to styles that live only in the docs.
